language: objective-c
osx_image: xcode10.2
xcode_project: LearnContinuousIntegration.xcodeproj
xcode_scheme: LearnContinuousIntegration
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
branches:
  only:
  - master
  - development
before_script:
- "./scripts/add-key.sh"
after_script:
- "./scripts/remove-key.sh"
script:
- "./scripts/build.sh"
env:
  global:
  - |
    - APP_NAME="LearnContinuousIntegration"
    - 'DEVELOPER_NAME="iPhone Distribution: Matheus Costa (Y93JMM3H2T)"'
    - PROFILE_NAME="Distribution"
    - IPA_NAME="LearnContinuousIntegration"
    - ARCHIVE_NAME="LearnContinuousIntegration_Dev"
  - secure: fI0GlV4nbXu1+oyaGuJsIGVLGN4heIHAcFkwv26JhCP9Jz/gKnMkuf64u4oM6sL8TQhlHYgpQv42lRvinlloupv+xv1PPenbzWXEn0IyWc05rE1FLq85j6ZqEy4SvEK2fZCxloF11wqj8qR6NfEBq4Kfq6H1KZwSEK3bZQv1ysCyZ5Yj1vnetkGX5qUzoYGKKNsCjRYRb+O9G8BV8HUi9Knh6ZOb4gYUODQedeuUPEUVxeN8t9U5tBrkrcL8lbbbEYxTv/sKt+rCk8nd5pYaGiDkMuoe58691QhDwma6vsKsa9B2SuyT6duL5qgRua05sSPXhuk81Ug/5+JM8HWy4TIA+ICV5gzEb4rIuPr0GzoJRQTvdThhHT4QsMuJMrAh/1mvF6exUr1U8whqicKHjf08Nnq0f3QH2kf0x67gpIemea+o3CAbfnxjzfIBe40sCVoEVTkSxIAgU4/EnNGuxOpcoFzGmzAYoruORDqp4X41dgmXUgmzs2/qZdTqoW0v0RuD/Jhuk6XBXP89/Tjs+ys8kIT2ZiaqTL04MFg82RNwD7sY2PjzIlImOIjgjZS5AB94aEgnOeU5oIrVZhrn33MtCod1wHSpqhDk8LA/I1cl0lddyda6CEPhxhCpjXH3Xwad3HBJ7I1QkJ+yp++RQwdcmlqm10lsyvvr0NMlZGg=
  - secure: ozQdbEmnKFSoUOOlRl6nzP8mymH9b2zahzCC9nvVkscclhk6CQOIEbOkcJXvZzvSt0NprHvCvBZL/QgE/l1Ku7PfEZ2hUrjrLgAZR9R+nzfwDfcnR8b9SZ2Q7NOE/Sw1SM0jFuNgB82EeXheA+EHbTNJCM8OwDGp88NZYmGZfyuzPXqhXoQALa7xUsyGVZs0UoFd0esZuh7fof2uZKp9+XEwuNBIuUfDE9ACJXm8TC41TBxzaSNmMBuPrgk1lqbbt3OkNhiIYf+AFDx5kz2s4v5Y9pM2ddtfzaZ3MN50bRywWUJVpqMkP69qqWPnXP92CX2mY2yPoLZKdfWL0tQsIFYVjtCkfYvxLJ3fmG0m+aDpt8fNyksHI71tGBWW/OwcO3G2xeYgG5KGvMdGYDUisqvuJNomgHk0H9Y4pnzBPklhqhmiwIQY48wgyThkP+E4oDsUbAfc+pDZeMaNspWcNiZ8sAjEeg/jBWDEV3V1zxZGY2m4frIu5FFSRPWyGMKW0TfwZlt6Kz7MRWbk13XOrKgy7a4kBHHJDiOcn3VEcNQXwkbuMRK9hSHAaSWgct4j4utgtkrbIeJegv5zzK326YUtxSp/UEyqo7QvT2NtfoBjwJdOFOJC5JJxhz+g0LCeJcWewAR+lnKmrlWXHTi8gr7chhEYC4n+/csv/gNd9L0=
  - secure: x+KNxXNwX7GLWAIEAduh6MiZsDKGHd/oPc80anzfGQeYDdhGN1nnob2XHFK957XBk4VHYySzt47tCcUgouQ5bZPGC2+i6MmH+ExZlyfNVweqp5IKFY+sRBd/HncJM3HEAfZhsGG69/gtq/taRcz6lGBWbTl8cCDUXuf4SSYX73X3mK49ASdlpB6m1QrMSCAxkbDivODWTf9fCmCt68LzDWaX+80QuPLVq6eKuBpJGL/1z4oRdyKhswe3vj6CoXsgfABLtuesWWKwqwHs2TgyFankxh8pr2+++U6U1pAybIYK+Mx8+Gx6MDQ9X6d30VKo3RgNhWWWf7vQSWDi+GumYzOdF/k3BkWud3yCMG1B1mnLiJbhzpTYvlK/R8oYNjoh2bx9U6INQ8ctvkn3fY3rftf2ERtdcJCYWe5atpY4vJ34yUAjyYExkutquahyC0TbVKc6Olou/EtSQzG7lgSYoqy6irb5mMmqeuUuQ7Y7KUI3tcsgGKnkBuXFnI++hnxVvYBnUvASBhGO6tIpO+kjiypUwG5/GDGPnRdpP6WfOZLYI+dQKGoViqiVR3tdm+zIMNoqeKw6uFcP3q5152l7jIq1nGNNacdPogr/nwy8KXGqWZYLB8Tmxe2qsIlpf354xriR0MrOVGCd0cFqDVlQq8G7cFT8B2mIXPwQRokCXfU=
